### ISSUE TITLE
Issues, Improvements and Feedback

### ISSUE THREAD

**Issue by theOllieS** [theOllieS/F1_Minisectors#2]
Please let me know any ways to improve this method please let me know as i would love to make it as good as it can be.
I'd like to work together to make it more functional.
Thanks!

**Comment by theOehrly** [comment]
Hi, I've finally had time to try your script. It worked as expected, so that's great. I do not have any suggestions right away on how you could improve accuracy or something like that. The remaining inaccuracies are likely due to the low sample rate and due to the data not being perfectly synchronized. I like your overall approach for the comparison. The results are, as I already commented, surprisingly good.
I do want to work on improving data synchronization in FastF1 for next season. And I will certainly use your script and the graphics that you have uploaded in #1 as a reference for that (among other things). Maybe I have some ideas and suggestions after using the script some more. But don't expect anything from me soon.
For now, nice work 👍

(If you really want something to work on, that'd be coding style. I found those style guides useless in the beginning. But after you get used to it, it really improves readability for yourself too. Use an editor that shows stylistic errors, and then it's not really that difficult. Although, I fully understand that if you're new to programming, it's an additional complicated thing to look out for. I taught myself programming and my code was horrible in the beginning 😂)

**Comment by siddharth-tewari** [comment]
@theOllieS Hello, I am having the following error. Can you please tell how to fix it?
```error
Traceback (most recent call last):
  File "C:\Users\Siddharth Tewari\Desktop\Formula 1\Fastest Laps\Telementry\F1_Minisectors\F1 minisectors.py", line 21, in <module>
    from ollie_color_scheme import *
  File "C:\Users\Siddharth Tewari\Desktop\Formula 1\Fastest Laps\Telementry\F1_Minisectors\ollie_color_scheme.py", line 14, in <module>
    fpath = os.path.join(rcParams["datapath"], "F1.ttf")
  File "C:\Users\Siddharth Tewari\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\__init__.py", line 674, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'datapath'
```

**Comment by theOllieS** [comment]
> @theOllieS Hello, I am having the following error. Can you please tell how to fix it?
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\Siddharth Tewari\Desktop\Formula 1\Fastest Laps\Telementry\F1_Minisectors\F1 minisectors.py", line 21, in <module>
>     from ollie_color_scheme import *
>   File "C:\Users\Siddharth Tewari\Desktop\Formula 1\Fastest Laps\Telementry\F1_Minisectors\ollie_color_scheme.py", line 14, in <module>
>     fpath = os.path.join(rcParams["datapath"], "F1.ttf")
>   File "C:\Users\Siddharth Tewari\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\__init__.py", line 674, in __getitem__
>     return dict.__getitem__(self, key)
> KeyError: 'datapath'
> ```


@siddharth-tewari It seems that there is an issue with the font cache possibly. 

For example in ollie_color_scheme on my own computer I have
`fpath = os.path.join(rcParams["datapath"], "/Users/olliesowden/.spyder-py3/F1 data/Formula1-Regular.ttf")`
Whereas you simply have just `"F1.ttf"`

perhaps if you try 

`fpath = os.path.join(rcParams["datapath"]," C:\Users\Siddharth Tewari\Desktop\Formula 1\/F1.ttf")`

or wherever you downloaded the f1 font to it should work. 

If this does not work I will create a simpler script with just the standard font and formatting as it will be easier to install, then just leave any customisation to the user.

**Comment by siddharth-tewari** [comment]
@theOllieS Still having this error.
```
Traceback (most recent call last):
  File "C:\Users\Siddharth Tewari\Desktop\Formula 1\Fastest Laps\Telementry\F1_Minisectors\F1 minisectors.py", line 21, in <module>
    from ollie_color_scheme import *
  File "C:\Users\Siddharth Tewari\Desktop\Formula 1\Fastest Laps\Telementry\F1_Minisectors\ollie_color_scheme.py", line 14, in <module>
    fpath = os.path.join(rcParams["datapath"], "Users\F1.ttf")
  File "C:\Users\Siddharth Tewari\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\__init__.py", line 674, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'datapath'
```

**Comment by theOllieS** [comment]
> @theOllieS Still having this error.

 Okay, I will try to upload a more basic script that still does effectively the same job sometime tonight.

**Comment by theOllieS** [comment]
@siddharth-tewari try this

https://github.com/theOllieS/F1_Minisectors/blob/main/Barebones%20F1%20Minisectors.py

**Comment by siddharth-tewari** [comment]
@theOllieS Thank You, now it works for me.

**Comment by siddharth-tewari** [comment]
@theOllieS My feedback for improvement would be adding legends on the side to identify the driver.

**Comment by theOllieS** [comment]
@siddharth-tewari Thanks. I played around with a legend but figured that the driver numbers would be clear enough. Do you mean something like this...
<img width="1438" alt="Screenshot 2021-12-14 at 11 14 02" src="https://user-images.githubusercontent.com/87935744/145988710-1f343a1a-e06c-420e-b4e4-bb9504f400e1.png">

**Comment by siddharth-tewari** [comment]
@theOllieS Yes, I meant this only. It would be fine without driver numbers too. I am having many colours while running the script.
![IMages](https://user-images.githubusercontent.com/76590952/145998379-daf49b0a-6699-4afe-93fe-89ea5a796dfa.jpg)

**Comment by theOllieS** [comment]
@siddharth-tewari I'm sorry if this wasn't clear. 

You can achieve a head to head of any drivers you would like if you use `driver_list = ['HAM', 'VER']` etc

The initial status is `driver_list = []` which automatically gives all drivers that completed quick laps. 


I managed to come up with a quick colorbar/legend 

`cbar = plt.colorbar(mappable=lc_comp, boundaries= bounds)`


# Get driver numbers
`labels = np.array(minisector_details['Fastest_driver_int']).astype(int)`
# Or have driver names 
`labels = driver_name_ordered`

# Get midpoint of numbers in list
`loc = num_list_ordered[:-1] + np.diff(num_list_ordered)/2`

`cbar.set_ticks(loc)`
`cbar.set_ticklabels(labels)`

seems to work nicely.  I would paste this in around line 230 of the code that I attached.

**Comment by siddharth-tewari** [comment]
@theOllieS Thank You

**Comment by siddharth-tewari** [comment]
@theOllieS Just a question, in barebone version or with custom fonts? I mean the legends' code and do we need to paste all of that in line 230?

**Comment by theOllieS** [comment]
> @theOllieS Just a question, in barebone version or with custom fonts? I mean the legends' code and do we need to paste all of that in line 230?

I have updated the barebones code with the legend

**Comment by siddharth-tewari** [comment]
@theOllieS Thank You for adding. Sorry, I didn't read the comments inside the document before running the code.

**Comment by hash55** [comment]
I'm sorry but, what's `driver_year_color` module, and how can I install it?

**Comment by theOehrly** [comment]
> I'm sorry but, what's `driver_year_color` module, and how can I install it?

It's just a separate python file. You need to download the full repository with all files so python can import from the other files.
Some constants like driver color are not in the main script.

**Comment by hash55** [comment]
> > I'm sorry but, what's `driver_year_color` module, and how can I install it?
> 
> It's just a separate python file. You need to download the full repository with all files so python can import from the other files. Some constants like driver color are not in the main script.

Ooops sorry, my bad

**Comment by theOllieS** [comment]
@hash55 It was just a solution that I came to when I wanted to analyse minisectors from pervious years, e.g. having VET in 2018 appearing in Aston Martin green didn't feel right, so I have accounted for every year since 2018 (when the telemetry data is available)

**Comment by siddharth-tewari** [comment]
@theOllieS You will have to add Hulkenburg in color scheme for Bahrain 2022. and Zhou too

**Comment by theOllieS** [comment]
Ah yes, thank you. You can simply copy and paste the 'VET' + hex code and replace with 'HUL' if you wish

**Comment by siddharth-tewari** [comment]
@theOllieS I already did that for myself.

**Comment by siddharth-tewari** [comment]
@theOllieS Do you have any idea to fix it right now?
![image](https://user-images.githubusercontent.com/76590952/159043734-b84cdc1f-0f61-44a8-8193-98dff41dc8a5.png)

**Comment by theOllieS** [comment]
This is due to the new fastf1 update. It should be resolved by replacing thing like session.weekend.year with session.event.year and so on

**Comment by siddharth-tewari** [comment]
@theOllieS I made a pull request for it.

> @theOllieS You will have to add Hulkenburg in color scheme for Bahrain 2022. and Zhou too
